[options]
; --- Base de datos ---
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo2026
db_name = pruebas

; --- Addons ---
addons_path = /home/pablo/odoo/addons, /home/pablo/odoo/addons/helpdesk, /home/pablo/odoo/odoo/addons

; --- Logs ---
logfile = logOdoo.log
log_level = debug

; --- Desarrollo ---
dev_mode = all

; --- Otros ---
default_productivity_apps = True