[options]
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo2026
admin_passwd = $pbkdf2-sha512$600000$sxaC0PpfC2GMUep9by2F0A$fUjhYfQI29wNCOFw8EzirAs5qUYcAFvL9zBqDgRO2PVyulGEVuy44EeCEg1EnlmquFAVHbHg3wGY98LucE6a/g
db_name = False
list_db = True
addons_path = /home/pablo/odoo/addons, /home/pablo/odoo/addons/helpdesk, /home/pablo/odoo/odoo/addons
logfile = logOdoo.log
log_level = debug
dev_mode = all
default_productivity_apps = True

