name: Trigger auto deployment for odoo-contel

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ 18.0 ]
    paths:
    - '**'
    - '.github/workflows/odoo-contel-AutoDeployTrigger-29fe4ab6-8194-4712-a607-946828efc671.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ODOOCONTEL_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ODOOCONTEL_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ODOOCONTEL_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: odoocontel-dygkd9bzcagcc9b7.azurecr.io
          registryUsername: ${{ secrets.ODOOCONTEL_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ODOOCONTEL_REGISTRY_PASSWORD }}
          containerAppName: odoo-contel
          resourceGroup: odoo
          imageToBuild: odoocontel-dygkd9bzcagcc9b7.azurecr.io/odoo-contel:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


