name: Trigger auto deployment for odoo-contel-prod

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ 18.0 ]
    paths:
    - '**'
    - '.github/workflows/odoo-contel-prod-AutoDeployTrigger-cd3aa530-2fd4-4f26-a055-6474a37cd1ea.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Checkout helpdesk module
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_ACCESO_REPOS }}
          repository: contelnet/helpdesk
          path: helpdesk
          
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.ODOOCONTELPROD_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: odoocontel-dygkd9bzcagcc9b7.azurecr.io
          registryUsername: ${{ secrets.ODOOCONTELPROD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ODOOCONTELPROD_REGISTRY_PASSWORD }}
          containerAppName: odoo-contel-prod
          resourceGroup: odoo
          imageToBuild: odoocontel-dygkd9bzcagcc9b7.azurecr.io/odoo-contel-prod:${{ github.sha }}
          
            

     

